spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/helpdesk
    username: helpdesk
    password: helpdesk
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
#    hibernate:
#      ddl-auto: create
  liquibase:
    change-log: classpath:liquibase-chagelog.xml
logging:
  level:
    database: DEBUG
