spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/helpdesk
    username: helpdesk
    password: helpdesk
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
#        jdbc:
#          time_zone: UTC
#        timezone:
#          default_storage: NORMALIZE
  #        use_sql_comments: true
  #        format_sql: true
        show-sql: true
  #    hibernate:
  #      ddl-auto: create
  liquibase:
    change-log: classpath:liquibase-chagelog.xml
  config:
    import: classpath:application-security.yml
#logging:
#  level:
#    org:
#      hibernate:
#        SQL: DEBUG
server:
  error:
    include-message: always
    include-binding-errors: always
logging:
  level:
    org:
      hibernate:
        SQL: trace
        type:
          descriptor:
            sql: trace
spring-doc:
  api-docs:
    enabled: true





